<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-PKCD9K85" failures="1" tests="3" name="Test" time="19.398" errors="0" timestamp="2023-11-23T20:51:46 IST">
  <testcase classname="com.ExtraaazDemo.testLayer.LoginTest" name="loginwithInValidCred" time="4.238"/>
  <testcase classname="com.ExtraaazDemo.testLayer.LoginTest" name="loginwithValidCred" time="5.698"/>
  <testcase classname="com.ExtraaazDemo.testLayer.RegistrationTest" name="registerUsingCredientials" time="5.2">
    <failure type="java.lang.AssertionError" message="expected [https://stg.extraaazpos.com/login] but found [https://stg.extraaazpos.com/register]">
      <![CDATA[java.lang.AssertionError: expected [https://stg.extraaazpos.com/login] but found [https://stg.extraaazpos.com/register]
at com.ExtraaazDemo.testLayer.RegistrationTest.registerUsingCredientials(RegistrationTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- registerUsingCredientials -->
  <testcase classname="com.ExtraaazDemo.testBase.TestBase" name="@BeforeTest start" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest start -->
  <testcase classname="com.ExtraaazDemo.testBase.TestBase" name="@AfterTest end" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest end -->
</testsuite> <!-- Test -->
