<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-23T20:51:26 IST" name="Suite" finished-at="2023-11-23T20:51:46 IST" duration-ms="19398">
    <groups>
    </groups>
    <test started-at="2023-11-23T20:51:26 IST" name="Test" finished-at="2023-11-23T20:51:46 IST" duration-ms="19398">
      <class name="com.ExtraaazDemo.testLayer.LoginTest">
        <test-method is-config="true" signature="start()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:26 IST" name="start" finished-at="2023-11-23T20:51:27 IST" duration-ms="105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:27 IST" name="setUp" finished-at="2023-11-23T20:51:28 IST" duration-ms="1440" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginwithInValidCred()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:28 IST" name="loginwithInValidCred" finished-at="2023-11-23T20:51:32 IST" duration-ms="4238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithInValidCred -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:32 IST" name="tearDown" finished-at="2023-11-23T20:51:33 IST" duration-ms="113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:33 IST" name="setUp" finished-at="2023-11-23T20:51:34 IST" duration-ms="977" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginwithValidCred()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:34 IST" name="loginwithValidCred" finished-at="2023-11-23T20:51:39 IST" duration-ms="5698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithValidCred -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:39 IST" name="tearDown" finished-at="2023-11-23T20:51:39 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="end()[pri:0, instance:com.ExtraaazDemo.testLayer.LoginTest@145f66e3]" started-at="2023-11-23T20:51:46 IST" name="end" finished-at="2023-11-23T20:51:46 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.ExtraaazDemo.testLayer.LoginTest -->
      <class name="com.ExtraaazDemo.testLayer.RegistrationTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ExtraaazDemo.testLayer.RegistrationTest@2a4fb17b]" started-at="2023-11-23T20:51:39 IST" name="setUp" finished-at="2023-11-23T20:51:40 IST" duration-ms="984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="registerUsingCredientials()[pri:0, instance:com.ExtraaazDemo.testLayer.RegistrationTest@2a4fb17b]" started-at="2023-11-23T20:51:40 IST" name="registerUsingCredientials" finished-at="2023-11-23T20:51:46 IST" duration-ms="5200" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://stg.extraaazpos.com/login] but found [https://stg.extraaazpos.com/register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://stg.extraaazpos.com/login] but found [https://stg.extraaazpos.com/register]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.ExtraaazDemo.testLayer.RegistrationTest.registerUsingCredientials(RegistrationTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerUsingCredientials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ExtraaazDemo.testLayer.RegistrationTest@2a4fb17b]" started-at="2023-11-23T20:51:46 IST" name="tearDown" finished-at="2023-11-23T20:51:46 IST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ExtraaazDemo.testLayer.RegistrationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
